version: "3.8"

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production

    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
