services:
  ryuko-matoi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ryuko-matoi
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production

    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
